


@set THISDIR=%CD%
@set THISDIRWITHPROPERSLASHES=%THISDIR:\=/%
@set THISDIRFROMHOSTROOT=%THISDIRWITHPROPERSLASHES:~2,100000%


@vagrant ssh -c "cd $HOSTROOT%THISDIRFROMHOSTROOT% && make %*"



