




@set THISDIR=%CD%
@set THISDIRWITHPROPERSLASHES=%THISDIR:\=/%
@set THISDIRFROMHOSTROOT=%THISDIRWITHPROPERSLASHES:~2,100000%

@set BLOCKWORKS_PLATFORM_BASEWITHPROPERSLASHES=%BLOCKWORKS_PLATFORM_BASE:\=/%
@set BLOCKWORKS_PLATFORM_BASEFROMHOSTROOT=%BLOCKWORKS_PLATFORM_BASEWITHPROPERSLASHES:~2,100000%

vagrant ssh -c "cd /HostRoot%THISDIRFROMHOSTROOT% && /HostRoot%BLOCKWORKS_BUILD_BASE%/Common/%BLOCKWORKS_TARGET_PLATFORM%/Debug %* -ex 'tar ext:4242' "



