




@set THISDIR=%CD%
@set THISDIRWITHPROPERSLASHES=%THISDIR:\=/%
@set THISDIRFROMHOSTROOT=%THISDIRWITHPROPERSLASHES:~2,100000%

@set BUILDDIR=%BLOCKWORKS_BUILD_BASE%
@set BUILDDIRWITHPROPERSLASHES=%BUILDDIR:\=/%
@set BUILDDIRFROMHOSTROOT=%BUILDDIRWITHPROPERSLASHES:~2,100000%

@set BLOCKWORKS_PLATFORM_BASEWITHPROPERSLASHES=%BLOCKWORKS_PLATFORM_BASE:\=/%
@set BLOCKWORKS_PLATFORM_BASEFROMHOSTROOT=%BLOCKWORKS_PLATFORM_BASEWITHPROPERSLASHES:~2,100000%

@call vagrant ssh-config > %TEMP%\sshConfig

@rem ssh -F %TEMP%\sshConfig default -T -C "cd /HostRoot%THISDIRFROMHOSTROOT% && /HostRoot%BUILDDIRFROMHOSTROOT%/Common/STM32/Debug %*  | sed "s/xxx/yyy/g" "
@ssh -F %TEMP%\sshConfig default -t -C "cd /HostRoot%THISDIRFROMHOSTROOT% && /HostRoot%BUILDDIRFROMHOSTROOT%/Common/STM32/Debug %* "


