





@set THISDIR=%CD%
@set DRIVELETTER=%CD:~0,1%

@set THISDIRWITHPROPERSLASHES=%THISDIR:\=/%
@set THISDIRFROMHOSTROOT=%THISDIRWITHPROPERSLASHES:~2,100000%



@set BUILDBASEDRIVELETTER=%BLOCKWORKS_BUILD_BASE:~0,1%
@set BUILDDIR=%BLOCKWORKS_BUILD_BASE%
@set BUILDDIRWITHPROPERSLASHES=%BUILDDIR:\=/%
@set BUILDDIRFROMHOSTROOT=%BUILDDIRWITHPROPERSLASHES:~2,100000%

@set BLOCKWORKS_PLATFORM_BASEWITHPROPERSLASHES=%BLOCKWORKS_PLATFORM_BASE:\=/%
@set BLOCKWORKS_PLATFORM_BASEFROMHOSTROOT=%BLOCKWORKS_PLATFORM_BASEWITHPROPERSLASHES:~2,100000%

@rem call vagrant ssh-config > %TEMP%\sshConfig


@set TARGET_DEBUG_SCRIPT=/HostRoot/%BUILDBASEDRIVELETTER%%BUILDDIRFROMHOSTROOT%/Common/STM32/Debug
@set TARGET_CWD=/HostRoot/%DRIVELETTER%%THISDIRFROMHOSTROOT%

@ssh $BLOCKWORKS_USERANDMACHINE -t -C "cd %TARGET_CWD% && %TARGET_DEBUG_SCRIPT% %* "


