#!/bin/bash


export ARGS_WITHOUT_PLATFORM=$@

#echo STM32 Debug script.
#echo $ARGS_WITHOUT_PLATFORM


#st-util & 
#gdbserverPID=$!

#echo pid is $gdbserverPID
arm-none-eabi-gdb $ARGS_WITHOUT_PLATFORM
#kill -9 $gdbserverPID
