#!/bin/bash

export THISDIRFROMHOSTROOT=/HostRoot`pwd`
echo $THISDIRFROMHOSTROOT

export args="$@"
vagrant ssh -c "export BLOCKWORKS_PLATFORM_BASE=/HostRoot$BLOCKWORKS_PLATFORM_BASE && cd $THISDIRFROMHOSTROOT && make $args"

