#!/bin/bash



export PLATFORM=`echo $* | sed -E "s/.*PLATFORM=([a-zA-Z0-9]+).*/\1/g"`
export ARGS_WITHOUT_PLATFORM=`echo $* | sed -E "s/PLATFORM=([a-zA-Z0-9]+)//g" `

echo target is: $PLATFORM
echo host is: $BLOCKWORKS_BUILD_HOSTTYPE
echo args without platform: $ARGS_WITHOUT_PLATFORM

vagrant ssh-config > sshConfig
source $BLOCKWORKS_BUILD_BASE/Common/$PLATFORM/Debug


