#!/bin/bash

export THISDIRFROMHOSTROOT=/HostRoot`pwd`
echo $THISDIRFROMHOSTROOT

export args="$@"
ssh -i /BlockWorks/Build/Common/PrivateKey $BLOCKWORKS_BUILDVM_USERHOST "export BLOCKWORKS_PLATFORM_BASE=/HostRoot$BLOCKWORKS_PLATFORM_BASE && cd $THISDIRFROMHOSTROOT && make $args"

